# Generated by Django 2.2 on 2019-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='measure',
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
