# Generated by Django 2.2 on 2019-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_attributevalue_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='measure',
        ),
        migrations.AddField(
            model_name='attribute',
            name='measure',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
