# Generated by Django 2.2 on 2019-04-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20190427_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.ProductType')),
            ],
        ),
    ]
