# Generated by Django 2.2 on 2019-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20190427_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
