# Generated by Django 2.2 on 2019-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20190504_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='some_slug'),
            preserve_default=False,
        ),
    ]
