# Generated by Django 2.2.1 on 2019-05-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_auto_20190516_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(),
        ),
    ]
